<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>disable</Nullable>
    <RootNamespace>LeveFinder</RootNamespace>
    <AssemblyName>LeveFinder</AssemblyName>
    <NoWarn>$(NoWarn);NETSDK1138</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\external\SaintCoinach\SaintCoinach\SaintCoinach.csproj" />
  </ItemGroup>
</Project>
